title: Cairenna Docs
description: Local setup, runtime options, and architecture details for the Cairenna mental health platform.
remote_theme: just-the-docs/just-the-docs@v0.10.1
plugins:
  - jekyll-include-cache
  - jekyll-seo-tag

url: https://cairenna-docs.github.io

aux_links:
  GitHub Repository: https://github.com/Soontosh/cairenna

callouts:
  note:
    title: Note
    color: purple
  warning:
    title: Warning
    color: red
